name: CI

on: [push]

jobs:
  test:
  
    strategy:
      matrix:
        luarocks_version: ["3.2.0"]
        lua_version: ["5.1"]

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
