name: CI

on: [push]

jobs:
  test:
    strategy:
      matrix:
        luarocks_version: ["3.2.0"]
        lua_version: ["5.1.5"]

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Install readline
      run: sudo apt-get install libreadline-dev
    - name: Install lua ${{ matrix.lua_version }}
      run: |
        mkdir -p .install
        LUA_INSTALL_DIR="$(pwd)/.lua"
        mkdir -p "$LUA_INSTALL_DIR"
        cd .install
        curl http://www.lua.org/ftp/lua-${{ matrix.lua_version }}.tar.gz | tar xz
        cd lua-${{ matrix.lua_version }}
        make -j linux
        make -j INSTALL_TOP="$LUA_INSTALL_DIR" install;
    - name: See what's up
      run: |
        pwd
        find .
    - name: Install luarocks ${{ matrix.luarocks_version }}
      run: |
        mkdir -p .install
        LUA_INSTALL_DIR="$(pwd)/.lua"
        LUAROCKS_INSTALL_DIR="$(pwd)/.luarocks"
        mkdir -p "$LUAROCKS_INSTALL_DIR"
        cd .install
        curl -L https://luarocks.org/releases/luarocks-${{ matrix.luarocks_version }}.tar.gz | tar xz
        cd luarocks-${{ matrix.luarocks_version }}
        ./configure --with-lua-bin="${LUA_INSTALL_DIR}/bin" --prefix="$LUAROCKS_INSTALL_DIR"



