name: test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        luaVersion: ["5.1.5", "luajit-openresty"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua/install-lua@master
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: leafo/gh-actions-lua/install-luarocks@master

    - name: build
      run: |
        eval $(.luarocks/bin/luarocks path)
        luarocks install busted
        luarocks install moonscript
        luarocks make
        busted -o utfTerminal

    - name: test
      run: |
        eval $(.luarocks/bin/luarocks path)
        busted -o utfTerminal

    - name: upload
      run: |
        eval $(.luarocks/bin/luarocks path)
        luarocks upload --force --api-key="${{ secrets.LUAROCKS_API_KEY }}" twitter-dev-1.rockspec
